# Generated by Django 4.2.5 on 2023-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTiendaVelezBeatriz', '0002_fabricante_articulos_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
